### ISSUE TITLE
Add a CircularProgressIndicator till the category images are loading 

### ISSUE THREAD

**Issue by harsh082ip** [harsh082ip/WallArtistry-flutter#1]

**Comment by JManan** [comment]
@harsh082ip where? tell the steps to produce.

**Comment by harsh082ip** [comment]
https://github.com/harsh082ip/WallArtistry-flutter/assets/109286547/99e8dad3-e09e-4a20-952a-8781fb7ebc2b

Here is a demo video, when we open the app, there is a blank space left in the category block till the images loads up, I want to add a CircularProgressIndicator tell the category block loads up, so we didn't have to see that blank space

**Comment by harsh082ip** [comment]
Issue Solved
